- hosts: localhost
  pre_tasks:
    - name: Update pacman cache
      become: true
      pacman:
        update_cache: yes
      tags:
      - general
      - ssh
      - fish
      - hypr
      - laptop
      - desktop
      - laptop_only
      - desktop_only
  tasks: 
    - include_tasks: ansible-tasks/general.yml
      tags:
      - general
      - desktop
      - laptop
    #- include_tasks: ansible-tasks/gitconfig.yml
    - include_tasks: ansible-tasks/ssh.yml
      tags:
      - ssh
      - desktop
      - laptop
    - include_tasks: ansible-tasks/fish.yml
      tags:
      - fish
      - desktop
      - laptop
    - include_tasks: ansible-tasks/hypr.yml
      tags:
      - hypr
      - desktop
      - laptop
    - include_tasks: ansible-tasks/laptop.yml
      tags:
      - laptop
      - laptop_only
    - include_tasks: ansible-tasks/desktop.yml
      tags:
      - desktop
      - desktop_only
    - include_tasks: ansible-tasks/yay.yml
      tags:
      - yay
      - desktop
      - laptop
    - include_tasks: ansible-tasks/yayapps.yml
      tags:
      - yayapps
      - desktop
      - laptop
