- hosts: localhost
  become: true
  pre_tasks:
    - name: Update pacman cache
      pacman:
        update_cache: yes
      tags:
      - general
      - fish
      - hypr
      - laptop
      - desktop
  tasks: 
    - include_tasks: ansible-tasks/general.yml
    #- include_tasks: ansible-tasks/gitconfig.yml
    #- include_tasks: ansible-tasks/ssh.yml
    - include_tasks: ansible-tasks/fish.yml
    - include_tasks: ansible-tasks/hypr.yml
    - include_tasks: ansible-tasks/laptop.yml
    - include_tasks: ansible-tasks/desktop.yml
     # Task symlink tmux-sessionizer to .local/bin/
      # Move tmux.conf to $HOME/tmux.conf
