- hosts: localhost
  become: true
  pre_tasks:
    - name: Update pacman cache
      pacman:
        update_cache: yes
      tags:
      - packages
      - fish
  tasks: 
    # - name: stow everything
    #   shell: stow -t ~ .config
    - include_tasks: ansible-tasks/packages.yml
    - include_tasks: ansible-tasks/fish.yml
     # Task stow tmux-sessionizer to .local/bin/
      # Move tmux.conf to $HOME/tmux.conf
