-- Themes
require("plugin_config.themes.kanagawa")
require("plugin_config.themes.onedark")
require("plugin_config.themes.rosepine")
-- 
require("plugin_config.lualine")
require("plugin_config.lsp")
require("plugin_config.telescope")
require("plugin_config.treesitter")
require("plugin_config.autosession")
require("plugin_config.fugitive")
--require("plugin_config.leap")
--require("plugin_config.refactoring")
require("plugin_config.conform")
require("plugin_config.vim-rest-console")
require("plugin_config.codeium")
