#!/usr/bin/env bash

sudo pacman -S hyprland hyprcursor hyprgraphics hypridle hyprland-protocols hyprland-qt-support hyprlang hyprlock hyprpaper hyprpolkitagent hyprutils hyprwayland-scanner xdg-desktop-portal-hyprland waybar grim slurp swappy swaync --noconfirm

yay -S rose-pine-hyprcursor
