require("plugin_config.theme")
--require("plugin_config.nvim-tree")
require("plugin_config.lualine")
require("plugin_config.coc")
require("plugin_config.telescope")
require("plugin_config.treesitter")
