rclone bisync /data/data/com.termux/files/home/storage/shared/Books ShaiHulud:Books -v

[ShaiHulud]
type = sftp
host = 192.168.1.253
port = 1337
user = ky
key_file =  $HOME/.ssh/id_ed25519
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum
