- block:
  - name: Ensure .ssh directory exists
    ansible.builtin.file:
      path: "~/.ssh"
      state: directory
      mode: '0700'
  - name: Decrypt the private SSH key file to the .ssh dir
    ansible.builtin.command:
      cmd: "ansible-vault decrypt ~/.dotfiles/.ssh/id_ed25519 --output ~/.ssh/id_ed25519"
  tags:
  - ssh
  - desktop
  - laptop
