- block:
  - name: Install librewolf
    become: true
    become_user: aur_builder
    ansible.builtin.command:
      cmd: yay -S librewolf-bin --noconfirm
    args:
      creates: /usr/bin/librewolf
  # - name: Install operator mono font
  #   become: true
  #   become_user: aur_builder
  #   ansible.builtin.command:
  #     cmd: yay -S otf-operator-mono-nerd --noconfirm
  tags:
  - yayapps
  - desktop
  - laptop
